simple:
  1:
    instruction: "Scoop the beans to the green bowl."
    tool: ['spoon', 'fork', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: pink
        food: ball
        color: ['red']
        amount: 1200
      - x: None
        y: None
        type: bowl
        container_color: green
        food: None
        color: ['red', 'purple']
        amount: 0
  2:
    instruction: "Stir the food in the bowl."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: yellow
        food: ball
        color: ['black', 'white']
        amount: 1200
      - x: None
        y: None
        type: bowl
        container_color: white
        food: None
        color: ['black', 'darkgreen']
        amount: 0
  3:
    instruction: "Cut the food"
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: cutting_board
        container_color: None
        food: cuttable_food
        color: None
        amount: None
      - x: None
        y: None
        type: square_plate
        container_color: None
        food: None
        color: None
        amount: None
  4:
    instruction: "Scoop the food to the empty plate"
    tool: ['spoon', 'fork', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: black
        food: ball
        color: ['red']
        amount: 1200
      - x: None
        y: None
        type: round_plate
        container_color: green
        food: None
        color: ['red', 'purple']
        amount: 20
  5:
    instruction: "Move to the plate with food with the fork held on the hand."
    tool: ['spoon', 'knife', 'fork']
    containers:
      - x: None
        y: None
        type: square_plate
        container_color: white
        food: None
        color: white
        amount: 0
      - x: None
        y: None
        type: round_plate
        container_color: white
        food: ball
        color: ['black']
        amount: 200
  6:
    instruction: "Put the beans into the bowl."
    tool: ['spoon', 'fork', 'knife']
    containers:
      - x: 0.5
        y: 0.2
        type: bowl
        container_color: pink
        food: ball
        color: ['red']
        amount: 2000
      - x: 0.38
        y: -0.25
        type: bowl
        container_color: green
        food: None
        color: ['red']
        amount: 1200
medium:
  1:
    instruction: "Stir food in the bowl then scoop it to the plate with food"
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: 0.5
        y: 0.
        type: bowl
        container_color: blue
        food: ball
        color: ['black', 'white']
        amount: 1200
      - x: 0.3
        y: 0.3
        type: square_plate
        container_color: gray
        food: forked_food
        color: ['black']
        amount: 1600
      - x: 0.35
        y: -0.3
        type: round_plate
        container_color: white
        food: None
        color: None
  2:
    instruction: "Move the red beans to all bowls and stir them."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: 0.5
        y: 0.5
        type: bowl
        container_color: white
        food: ball
        color: ['red']
        amount: 1600
      - x: 0.35
        y: 0.8
        type: bowl
        container_color: gray
        food: None
        color: ['black']
        amount: 1600
      - x: 0.35
        y: 0.2
        type: bowl
        container_color: black
        food: None
        color: None
      - x: -0.3
        y: 0.8
        type: bowl
        container_color: purple
        food: None
        color: None
  3:
    instruction: "Cut the food, then scoop some of it into the empty bowl."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: 0.5
        y: 0.5
        type: bowl
        container_color: blue
        food: ball
        color: ['red']
        amount: 1600
      - x: 0.35
        y: 0.8
        type: bowl
        container_color: red
        food: None
        color: ['black']
        amount: 1600
      - x: 0.35
        y: 0.2
        type: cutting_board
        container_color: black
        food: cuttable_food
        color: None
  4:
    instruction: "Scoop the food into the bowl and scoop it to the plate."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: pink
        food: ball
        color: ['white', 'black']
        amount: 1600
      - x: None
        y: None
        type: round_plate
        container_color: gray
        food: None
        color: ['black']
        amount: 1600
      - x: None
        y: None
        type: bowl
        container_color: purple
        food: None
        color: None
  5:
    instruction: "Stir the food in one bowl, transfer it to another bowl."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: darkgray
        food: ball
        color: ['black']
        amount: 1600
      - x: None
        y: None
        type: bowl
        container_color: lightblue
        food: None
        color: ['green', 'pink']
        amount: 1600
      - x: None
        y: None
        type: cutting_board
        container_color: white
        food: None
        color: None
  6:
    instruction: "Scoop the green bean into the purple bowl."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: 0.8
        y: 0.1
        type: bowl
        container_color: darkgray
        food: ball
        color: ['green']
        amount: 1200
      - x: None
        y: None
        type: bowl
        container_color: lightblue
        food: ball
        color: ['red']
        amount: 800
      - x: None
        y: None
        type: bowl
        container_color: purple
        food: None
        color: None
  7:
    instruction: "Scoop some red bean to the bowl with green bean."
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: darkgray
        food: ball
        color: ['green']
        amount: 2700
      - x: None
        y: None
        type: bowl
        container_color: lightblue
        food: ball
        color: ['green']
        amount: 800
      - x: None
        y: None
        type: bowl
        container_color: purple
        food: ball
        color: ['red']
        amount: 1600
  8:
    instruction: "Put the bowl with beans into the microwave."
    tool: ['spoon', 'fork', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: gray
        food: ball
        color: ['green']
        amount: 1200
  9:
    instruction: "Put the bowl with beans into the microwave."
    tool: ['spoon', 'fork', 'knife']
    containers:
      - x: 0.45
        y: 0.28
        type: bowl
        container_color: red
        food: ball
        color: ['green']
        amount: 1200
hard:
  1:
    instruction: "Cut the food first then scoop some food on the cutted food"
    tool: ['fork', 'spoon', 'knife']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: white
        food: ball
        color: ['brown']
        amount: 1200
      - x: None
        y: None
        type: cutting_board
        container_color: white
        food: cuttable_food
        color: None
        amount: None
      - x: None
        y: None
        type: bowl
        container_color: gray
        food: None
        color: None
      - x: None
        y: None
        type: square_plate
        container_color: black
        food: None
        color: None
  2:
    instruction: "Stir the beans twice then scoop them to all empty bowls."
    tool: ['fork', 'knife', 'spoon']
    containers:
      - x: None
        y: None
        type: bowl
        container_color: white
        food: ball
        color: ['green', 'red']
        amount: 1200
      - x: None
        y: None
        type: bowl
        container_color: gray
        food: None
      - x: None
        y: None
        type: bowl
        container_color: black
        food: None
      - x: None
        y: None
        type: bowl
        container_color: darkgray
        food: None
  3:
    instruction: "Prepare the bean mixture and scoop it into the empty bowl."
    tool: ["fork", "knife", "spoon"]
    containers:
    - x: None
      y: None
      type: bowl
      container_color: yellow
      food: ball
      color: ['darkred', 'black']
      amount: 1200
    - x: None
      y: None
      type: bowl
      container_color: black
      food: ball
      color: ['lightyellow']
      amount: 1100
    - x: None
      y: None
      type: bowl
      container_color: purple
      food: None
  4:
    instruction: "Spread some beans on the butter and take fork."
    tool: ["spoon", "fork", "knife"]
    containers:
    - x: None
      y: None
      type: bowl
      container_color: white
      food: ball
      color: ['darkgreen']
      amount: 1200
    - x: None
      y: None
      type: square_plate
      container_color: white
      food: forked_food
      color: None
      amount: None
  5:
    instruction: "Make a bowl of meal consisting of red beans, green beans and black beans in a ratio of 3:2:1."
    tool: ["knife", "spoon"]
    containers:
    - x: None
      y: None
      type: bowl
      container_color: gray
      food: ball
      color: ['green']
      amount: 1200
    - x: None
      y: None
      type: bowl
      container_color: lightgray
      food: ball
      color: ['red']
      amount: 1200
    - x: None
      y: None
      type: bowl
      container_color: darkgray
      food: ball
      color: ['black']
      amount: 1200
    - x: None
      y: None
      type: bowl
      container_color: white
      food: None
  6:
    instruction: "Scoop some green ball into the empty bowl."
    tool: ['spoon', 'fork', 'knife']
    containers:
    - x: None
      y: None
      type: bowl
      container_color: lightblue
      food: None
      color: None
      amount: None
    - x: None
      y: None
      type: bowl
      container_color: darkblue
      food: ball
      color: ['green']
      amount: 1200
  7:
    instruction: "None, just for testing."
    tool: ['spoon', 'fork', 'knife']
    containers:
    - x: 0.4
      y: 0.25
      type: bowl
      container_color: white
      food: ball
      color: ['green']
      amount: 1800
    - x: 0.6
      y: 0.25
      type: bowl
      container_color: white
      food: ball
      color: ['darkred']
      amount: 1800
    - x: 0.4
      y: 0.05
      type: bowl
      container_color: white
      food: ball
      color: ['salmon']
      amount: 1800
    - x: 0.6
      y: 0.05
      type: bowl 
      container_color: white
      food: ball
      color: ['black']
      amount: 1800
    - x: 0.7
      y: -0.18
      type: bowl
      container_color: yellow
      food: None
      color: ['black']
      amount: None
    