# scoop, scoop_put, pull_the_bowl, put and take out the bowl in microwave
# different amounts of beans
# different distance of beans
# bowls block the spoon (pull the bowl)
# bowls block the door (pull bowl)
# objects in the microwave so that other objects could not put in (put bowl in microwave | take out bowl in microwave)
# beans are too far (pull the bowl)
# general scooping