distance:
  1:
    instruction: Scoop mung beans to the blue bowl.
    answer: [grasp_spoon, move_to_white_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.718807468361423
      y: -0.08577563045108634
      type: bowl
      color: white
      colorcode: antiquewhite
      food:
        type: ball
        color: [mung]
        colorcode: [darkgreen]
        amount: 1600
        position: [1, 1]
    - x: 0.5242868350317109
      y: 0.16533738534543196
      type: bowl
      color: blue
      colorcode: navy
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  2:
    instruction: Please scoop beans from purple bowl to white bowl.
    answer: [grasp_spoon, move_to_purple_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7133848904403666
      y: 0.021359146694553743
      type: bowl
      color: purple
      colorcode: indigo
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.5184694011794374
      y: -0.1824557499091891
      type: bowl
      color: white
      colorcode: papayawhip
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  3:
    instruction: Transfer red beans to the empty bowl.
    answer: [grasp_spoon, move_to_green_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7124733439081468
      y: -0.026946218814053652
      type: bowl
      color: green
      colorcode: palegreen
      food:
        type: ball
        color: [red]
        colorcode: [darkred]
        amount: 1600
        position: [1, 1]
    - x: 0.4043663444108435
      y: 0.1949601150960757
      type: bowl
      color: purple
      colorcode: mediumpurple
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  4:
    instruction: Put a scoop of speckled beans in the red bowl please.
    answer: [grasp_spoon, move_to_blue_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.71
      y: -0.07260655099207335
      type: bowl
      color: blue
      colorcode: cornflowerblue
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.4247792080598537
      y: 0.1544866433750815
      type: bowl
      color: red
      colorcode: darkred
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  5:
    instruction: Scoop beans into the empty bowl.
    answer: [grasp_spoon, move_to_blue_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7116981861410818
      y: 0.11501109399345363
      type: bowl
      color: blue
      colorcode: darkslateblue
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.4702187212307981
      y: -0.17172198750212272
      type: bowl
      color: white
      colorcode: lightgrey
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  6:
    instruction: Scoop speckled beans into the grey bowl please.
    answer: [grasp_spoon, move_to_pink_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7148769908465695
      y: 0.02180612680496266
      type: bowl
      color: pink
      colorcode: pink
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.470931795274238
      y: -0.1894831950914108
      type: bowl
      color: grey
      colorcode: slategrey
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  7:
    instruction: Please scoop beans from the bowl with beans to the empty bowl.
    answer: [grasp_spoon, move_to_white_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7105463435475741
      y: -0.1383348224273601
      type: bowl
      color: white
      colorcode: antiquewhite
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.36461166197268696
      y: 0.167738482363805
      type: bowl
      color: blue
      colorcode: deepskyblue
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  8:
    instruction: Please scoop beans from a bowl to another bowl.
    answer: [grasp_spoon, move_to_white_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7106356481586467
      y: 0.1
      type: bowl
      color: white
      colorcode: papayawhip
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.37281732563381137
      y: -0.0978551733647646
      type: bowl
      color: purple
      colorcode: violet
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  9:
    instruction: Transfer a scoop of beans in the grey bowl to the purple bowl.
    answer: [grasp_spoon, move_to_grey_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7124368877362324
      y: 0.0
      type: bowl
      color: grey
      colorcode: slategrey
      food:
        type: ball
        color: [mung]
        colorcode: [darkgreen]
        amount: 1600
        position: [1, 1]
    - x: 0.5428882633302237
      y: -0.1507825930231831
      type: bowl
      color: purple
      colorcode: violet
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
  10:
    instruction: Scoop food to the purple bowl.
    answer: [grasp_spoon, move_to_blue_bowl,
      scoop, DONE]
    tool: [spoon]
    containers:
    - x: 0.7127473632004931
      y: 0.0
      type: bowl
      color: blue
      colorcode: navy
      food:
        type: ball
        color: [speckled]
        colorcode: [peru]
        amount: 1600
        position: [1, 1]
    - x: 0.4343304409260512
      y: 0.2379009706896899
      type: bowl
      color: purple
      colorcode: violet
      food:
        type: None
        color: []
        colorcode: []
        amount: 0
        position: [1, 1]
